language: python
python:
- 3.5
env:
- pipenv
install:
- pipenv install
script:
- py.test --cov=tests
branches:
  only:
    - master
deploy:
  - provider:heroku
  api_key:
    secure: egLeTApi+EOVqNgxePGscLWOduq3VRYTcVoae7czTFsG6u5MLP7jQmUerxF8cq6L7bq4+ahOyhetD7pd4kUDVDT+pAg9fd9aIhxpvU5EyrcFtpS816lT+gfq8VJ+1A4c9WEZhePVW37J2Z6QmJTyq4F7odoTydRIHw2kN1Cv/fbbiAiDQDqh3HWR0aXU401AQvAoWaqoSZJmQIMa5+9vh00/rfvUR7sbTuFbVXGHBrInV0QOfdodPg6J+IjEwM1S8qOSeOpbFfODPtP39IMt2h1E008CCXjAmE0cs0YlNyAg8UpY5kTGjqfWjdRZIh4Hdl92qmwwBwAqi9Yia1Iwzdi18c42Gk/yL8tyIEbee+EHcAaP+8tcQ6RxWh6B4QKvvsDNddzoJyzVjoM/U01+TCugOkCK9lvmTqca22zS/+2AwrzJ+XoYvLSPeokK5Bbcs85JdnLjtEFQbtUiGqJe4ME23cPMgswoNE6DnRhz9HXKIG1N55cAFYDE70iAA8KrGwY1NmHr6yUFIk/h+p8jbyWU2ovmmKabDiHja64H2I9MrDXLb0GprYkPBQO/xfsjrTOlt6wDh/Dv+4AASCJwKmuN/riDjLuCLW7p5dFi0/FYNWLHnbq/3bADVF8Z2ch73JROXTRrAmnoiKYhM5TdAjVJQAqKgHof8vurbtRnaKY=
    app: flaskapptm
