language: python
python:
- 3.5
env:
- pipenv
install:
- pipenv install
script:
- py.test --cov=tests
deploy:
  provider: heroku
  api_key:
    secure: OtQ1nsHcAfPLdfUU6eb7CH0ou1BcX8/BnJbC8pRK8CJ4WZwVDcfwgRAHB4q5TtqN2M3yBPuu4OzDhVLPO1QBxOOvyjCXAteqdJTdi+MFR2QqBaflKXak4bQG0uZ+S27CLEopusMFXDQoW0rCkcxYDm3fpFsDyO4ykyXw79DPvXJRnc2NxFjgvwHYuV9+s5ZZ7Hm3LozGmAmJSi4RQNbexpZNBzCNKR7pjKSLrwqeiQXoSQgioiglSFTDOc5iyvwQ53w8CVV4GxDBjJbYwziNoXY4/E92akNmiHt5AoA68sQ2++kXz2SqdzThBEv4aNtV9/nEFlEe3OCaYUIvw4eA24l9p8kNXGPXFUhKqzOGDihS14J79EvP4++zYH48l5rUm+8XdlqVlZ+vrIY5C5QK6cBSb9LniPrhQVVuilEEdyNXiykLSRaO7/vlZtTSPv5olcMuO5hXQtPCMjvBX90gfdZdrPB5zduxHI18kv1z2LMvQWzGiTlTnZ+DLz0vONRAoCoQ7NTQhmSfX6KYfxtC4LrvP8Fw1gkVvAMUvrg2vSnBwaei76CiXyqmhgQeZlYjD1v1R6hS2tHxH+9StnzwxgS8xuSQ48F31BJgBMcGBLsZvOk4fmVzgGptLfRyfehJ12VvaURMSdJcWcNZWJ2UD3LRp3C9neNIp/6Bw4ObtE0=
